// <auto-generated />
namespace Proje.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addingPropDeletedAndDrafted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingPropDeletedAndDrafted));
        
        string IMigrationMetadata.Id
        {
            get { return "202106300737145_addingPropDeletedAndDrafted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
